# Generated by Django 3.2.1 on 2021-05-06 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20210506_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classcategory',
            name='title',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
