# Generated by Django 3.2.1 on 2021-05-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20210506_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiPostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.post')),
                ('wiki_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.wikifile')),
            ],
        ),
    ]
