# Generated by Django 3.2.2 on 2021-05-12 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_wikifile_wikipostfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikifile',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.classcategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.mastercategory', verbose_name='Haupt-Kategorie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(default='', verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='wikifile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
