# Generated by Django 3.2.2 on 2021-05-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20210512_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSiteContent',
            fields=[
                ('site_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
