# Generated by Django 3.2.2 on 2021-05-15 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_classcategory_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
